import type { Metadata } from "next";
import { Birthstone } from "next/font/google"; 
import "./globals.css";


const birthstone = Birthstone({ 
  variable: "--font-birthstone", 
  weight: "400", 
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Happy Birthday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${birthstone.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
