import type { Metadata } from "next";
import { Geist, Geist_Mono, Birthstone } from "next/font/google"; 
import "./globals.css";


const pacifico = Birthstone({ 
  variable: "--font-pacifico", 
  weight: "400", 
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Happy Birthday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
